import type { WalletAppState } from './types'
import { SUPPORTED_CURRENCIES } from '../../../shared/constants/wallet'

export const initialWalletState: WalletAppState = {
  pools: SUPPORTED_CURRENCIES.map((currency) => {
    if (currency === 'INR') {
      return {
        currency,
        totalAddedMinor: 1500000,
        totalSpentMinor: 200000,
        totalAllocatedMinor: 1100000,
        unallocatedMinor: 400000,
      }
    }

    return {
      currency,
      totalAddedMinor: 0,
      totalSpentMinor: 0,
      totalAllocatedMinor: 0,
      unallocatedMinor: 0,
    }
  }),
  wallets: [
    { id: 'w-1', name: 'Daily Pocket', currency: 'INR', balanceMinor: 330000, purpose: 'daily', color: '#0a0a0a' },
    { id: 'w-2', name: 'Bills Vault', currency: 'INR', balanceMinor: 290000, purpose: 'bills', color: '#1d4ed8' },
    { id: 'w-3', name: 'Travel Fund', currency: 'INR', balanceMinor: 80000, purpose: 'travel', color: '#059669' },
    { id: 'w-4', name: 'Emergency Safe', currency: 'INR', balanceMinor: 200000, purpose: 'savings', color: '#7c3aed' },
  ],
  bankAccounts: [
    { id: 'b-1', bankName: 'State Bank', accountHolder: 'Primary User', accountLast4: '9001', currency: 'INR' },
    { id: 'b-2', bankName: 'HDFC Bank',  accountHolder: 'Primary User', accountLast4: '4472', currency: 'INR' },
    { id: 'b-3', bankName: 'ICICI Bank', accountHolder: 'Primary User', accountLast4: '2204', currency: 'INR' },
  ],
  transactions: [
    {
      id: 't-1',
      type: 'income',
      status: 'completed',
      currency: 'INR',
      amountMinor: 1000000,
      note: 'Monthly salary credited to pool',
      source: 'Salary',
      createdAtIso: '2026-05-01T09:30:00.000Z',
    },
    {
      id: 't-2',
      type: 'bank_to_wallet',
      status: 'completed',
      currency: 'INR',
      amountMinor: 500000,
      fromBankAccountId: 'b-1',
      note: 'Bank top-up to total pool',
      createdAtIso: '2026-05-02T10:15:00.000Z',
    },
    {
      id: 't-3',
      type: 'allocate_to_wallet',
      status: 'completed',
      currency: 'INR',
      amountMinor: 400000,
      toWalletId: 'w-1',
      note: 'Allocate daily budget',
      createdAtIso: '2026-05-03T09:00:00.000Z',
    },
    {
      id: 't-4',
      type: 'allocate_to_wallet',
      status: 'completed',
      currency: 'INR',
      amountMinor: 300000,
      toWalletId: 'w-2',
      note: 'Allocate bills reserve',
      createdAtIso: '2026-05-03T09:10:00.000Z',
    },
    {
      id: 't-5',
      type: 'allocate_to_wallet',
      status: 'completed',
      currency: 'INR',
      amountMinor: 200000,
      toWalletId: 'w-3',
      note: 'Allocate travel budget',
      createdAtIso: '2026-05-03T09:20:00.000Z',
    },
    {
      id: 't-6',
      type: 'allocate_to_wallet',
      status: 'completed',
      currency: 'INR',
      amountMinor: 200000,
      toWalletId: 'w-4',
      note: 'Allocate emergency savings',
      createdAtIso: '2026-05-03T09:30:00.000Z',
    },
    {
      id: 't-7',
      type: 'expense',
      status: 'completed',
      currency: 'INR',
      amountMinor: 50000,
      fromWalletId: 'w-1',
      note: 'Groceries and supplies',
      category: 'food',
      paymentType: 'card',
      tags: [],
      createdAtIso: '2026-05-10T19:00:00.000Z',
    },
    {
      id: 't-8',
      type: 'spend',
      status: 'completed',
      currency: 'INR',
      amountMinor: 30000,
      fromWalletId: 'w-2',
      note: 'Phone bill auto-pay',
      createdAtIso: '2026-05-14T08:10:00.000Z',
    },
    {
      id: 't-9',
      type: 'internal_transfer',
      status: 'completed',
      currency: 'INR',
      amountMinor: 20000,
      fromWalletId: 'w-1',
      toWalletId: 'w-2',
      note: 'Move balance for utilities',
      createdAtIso: '2026-05-16T12:00:00.000Z',
    },
    {
      id: 't-10',
      type: 'bank_transfer',
      status: 'completed',
      currency: 'INR',
      amountMinor: 120000,
      fromWalletId: 'w-3',
      toBankAccountId: 'b-2',
      note: 'Move travel reserve back to bank',
      createdAtIso: '2026-05-20T15:45:00.000Z',
    },
  ],
}
