import type { WalletAppState } from './types'

export const initialWalletState: WalletAppState = {
  wallets: [
    { id: 'w-1', name: 'Daily Pocket', currency: 'INR', balanceMinor: 2450000,  purpose: 'daily',   color: '#0a0a0a' },
    { id: 'w-2', name: 'Bills Vault',  currency: 'INR', balanceMinor: 8500000,  purpose: 'bills',   color: '#1d4ed8' },
    { id: 'w-3', name: 'Travel Fund',  currency: 'INR', balanceMinor: 7500000,  purpose: 'travel',  color: '#059669' },
    { id: 'w-4', name: 'India Family', currency: 'INR', balanceMinor: 18500000, purpose: 'savings', color: '#7c3aed' },
  ],
  bankAccounts: [
    { id: 'b-1', bankName: 'State Bank', accountHolder: 'Primary User', accountLast4: '9001', currency: 'INR' },
    { id: 'b-2', bankName: 'HDFC Bank',  accountHolder: 'Primary User', accountLast4: '4472', currency: 'INR' },
    { id: 'b-3', bankName: 'ICICI Bank', accountHolder: 'Primary User', accountLast4: '2204', currency: 'INR' },
  ],
  transactions: [
    {
      id: 't-1',
      type: 'expense',
      status: 'completed',
      currency: 'INR',
      amountMinor: 25000,
      fromWalletId: 'w-1',
      note: 'Coffee and snacks',
      category: 'food',
      paymentType: 'card',
      tags: ['morning', 'routine'],
      createdAtIso: '2026-05-23T09:20:00.000Z',
    },
    {
      id: 't-2',
      type: 'expense',
      status: 'completed',
      currency: 'INR',
      amountMinor: 85000,
      fromWalletId: 'w-1',
      note: 'Cab to airport',
      category: 'transport',
      paymentType: 'upi',
      tags: [],
      createdAtIso: '2026-05-23T07:45:00.000Z',
    },
    {
      id: 't-3',
      type: 'income',
      status: 'completed',
      currency: 'INR',
      amountMinor: 12000000,
      toWalletId: 'w-1',
      note: 'Monthly salary',
      source: 'Salary',
      createdAtIso: '2026-05-22T10:00:00.000Z',
    },
    {
      id: 't-4',
      type: 'internal_transfer',
      status: 'completed',
      currency: 'INR',
      amountMinor: 500000,
      fromWalletId: 'w-1',
      toWalletId: 'w-2',
      note: 'Move to bill reserve',
      createdAtIso: '2026-05-22T13:00:00.000Z',
    },
    {
      id: 't-5',
      type: 'expense',
      status: 'completed',
      currency: 'INR',
      amountMinor: 320000,
      fromWalletId: 'w-2',
      note: 'Electricity bill',
      category: 'bills',
      paymentType: 'bank_transfer',
      tags: ['utilities'],
      createdAtIso: '2026-05-21T18:30:00.000Z',
    },
    {
      id: 't-6',
      type: 'expense',
      status: 'completed',
      currency: 'INR',
      amountMinor: 64900,
      fromWalletId: 'w-1',
      note: 'Netflix subscription',
      category: 'entertainment',
      paymentType: 'card',
      tags: ['subscription'],
      createdAtIso: '2026-05-20T12:00:00.000Z',
    },
    {
      id: 't-7',
      type: 'expense',
      status: 'completed',
      currency: 'INR',
      amountMinor: 450000,
      fromWalletId: 'w-1',
      note: 'Weekend groceries',
      category: 'food',
      paymentType: 'card',
      tags: [],
      createdAtIso: '2026-05-19T15:00:00.000Z',
    },
    {
      id: 't-8',
      type: 'income',
      status: 'completed',
      currency: 'INR',
      amountMinor: 2500000,
      toWalletId: 'w-1',
      note: 'Freelance project payment',
      source: 'Freelance',
      createdAtIso: '2026-05-18T11:00:00.000Z',
    },
  ],
}
